#!/usr/bin/env bash
# =============================================================================
# generate-networkpolicy.sh — Generate NetworkPolicy for a namespace or workload
# =============================================================================
# Implements: CAPABILITIES.md Responder #6 (NetworkPolicy Generator)
# Rank: D (auto-approved when automated)
#
# Generates deny-all or workload-specific NetworkPolicies. Always allows
# kube-dns egress (UDP 53). Only applies to cluster with --apply flag.
#
# Usage:
#   bash generate-networkpolicy.sh --namespace production                     # default-deny
#   bash generate-networkpolicy.sh --namespace production --workload nginx    # workload-specific
#   bash generate-networkpolicy.sh --namespace production --deny-all          # deny-all ingress+egress
#   bash generate-networkpolicy.sh --namespace production --output policy.yaml
#   bash generate-networkpolicy.sh --namespace production --apply
# =============================================================================
set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

# --- Defaults ---
NAMESPACE=""
WORKLOAD=""
DENY_ALL=false
APPLY=false
OUTPUT=""
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)

# --- Usage ---
usage() {
    cat <<'USAGE'
Usage: generate-networkpolicy.sh --namespace NS [OPTIONS]

Options:
  --namespace NS       Target namespace (required)
  --workload NAME      Generate policy for specific workload (uses app= label)
  --deny-all           Generate deny-all ingress + egress for namespace
  --output FILE        Output file path (default: networkpolicy-NS-TIMESTAMP.yaml)
  --apply              Apply the generated policy to the cluster
  -h, --help           Show this help

Modes:
  Default (no flags):  Namespace default-deny ingress only
  --deny-all:          Namespace deny-all ingress AND egress
  --workload NAME:     Workload-specific policy (deny all + allow DNS egress)

Examples:
  # Default deny ingress for namespace
  bash generate-networkpolicy.sh --namespace production

  # Deny all ingress + egress
  bash generate-networkpolicy.sh --namespace production --deny-all

  # Workload-specific (allow DNS only)
  bash generate-networkpolicy.sh --namespace production --workload nginx

  # Generate and apply
  bash generate-networkpolicy.sh --namespace production --deny-all --apply
USAGE
    exit "${1:-0}"
}

# --- Parse args ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --namespace)  NAMESPACE="$2"; shift 2 ;;
        --workload)   WORKLOAD="$2"; shift 2 ;;
        --deny-all)   DENY_ALL=true; shift ;;
        --apply)      APPLY=true; shift ;;
        --output)     OUTPUT="$2"; shift 2 ;;
        -h|--help)    usage 0 ;;
        *)            echo -e "${RED}ERROR: Unknown option: $1${NC}"; usage 1 ;;
    esac
done

if [[ -z "$NAMESPACE" ]]; then
    echo -e "${RED}ERROR: --namespace is required${NC}"
    usage 1
fi

# --- Set output file ---
if [[ -z "$OUTPUT" ]]; then
    OUTPUT="networkpolicy-${NAMESPACE}-${TIMESTAMP}.yaml"
fi

# --- Generate policy ---
echo -e "${CYAN}Generating NetworkPolicy...${NC}"

if [[ -n "$WORKLOAD" ]]; then
    # ----- Workload-specific policy -----
    POLICY_NAME="gp-netpol-${WORKLOAD}"
    echo -e "  Mode: workload-specific (${WORKLOAD})"
    echo -e "  Allows: kube-dns egress (UDP 53)"
    echo -e "  Blocks: all other ingress + egress"

    # Verify workload exists (best-effort: check for pods with app= label)
    POD_COUNT=$(kubectl get pods -n "$NAMESPACE" -l "app=${WORKLOAD}" --no-headers 2>/dev/null | wc -l || echo 0)
    if [[ "$POD_COUNT" -eq 0 ]]; then
        echo -e "${YELLOW}  WARNING: No pods found with label app=${WORKLOAD} in ${NAMESPACE}${NC}"
        echo -e "${YELLOW}  The policy will be generated but may not match any pods.${NC}"
    else
        echo -e "${GREEN}  Found ${POD_COUNT} pod(s) matching app=${WORKLOAD}${NC}"
    fi

    cat > "$OUTPUT" <<EOF
# Generated by GP-Copilot generate-networkpolicy.sh
# Workload-specific NetworkPolicy for: ${WORKLOAD}
# Namespace: ${NAMESPACE}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Effect: Deny all ingress and egress EXCEPT kube-dns (UDP 53)
# To add more rules, append to the ingress/egress arrays below.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${POLICY_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: gp-copilot
    gp-copilot/responder: networkpolicy-generator
  annotations:
    gp-copilot/generated-at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    gp-copilot/workload: "${WORKLOAD}"
spec:
  podSelector:
    matchLabels:
      app: ${WORKLOAD}
  policyTypes:
    - Ingress
    - Egress
  # No ingress rules = deny all inbound
  ingress: []
  egress:
    # Allow DNS resolution (required for most workloads)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
EOF

elif [[ "$DENY_ALL" == true ]]; then
    # ----- Namespace deny-all (ingress + egress) -----
    POLICY_NAME="gp-deny-all-${NAMESPACE}"
    echo -e "  Mode: deny-all ingress + egress for namespace"

    cat > "$OUTPUT" <<EOF
# Generated by GP-Copilot generate-networkpolicy.sh
# Deny-all NetworkPolicy for namespace: ${NAMESPACE}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Effect: Block ALL ingress and egress for all pods in this namespace.
# WARNING: This blocks DNS too. Pods will not be able to resolve hostnames.
# Add workload-specific policies to allow required traffic.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${POLICY_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: gp-copilot
    gp-copilot/responder: networkpolicy-generator
  annotations:
    gp-copilot/generated-at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  # No rules = deny all traffic in both directions
EOF

else
    # ----- Default deny ingress only -----
    POLICY_NAME="gp-default-deny-${NAMESPACE}"
    echo -e "  Mode: default-deny ingress for namespace"
    echo -e "  Egress is NOT blocked (pods can still reach external services)"

    cat > "$OUTPUT" <<EOF
# Generated by GP-Copilot generate-networkpolicy.sh
# Default-deny ingress NetworkPolicy for namespace: ${NAMESPACE}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Effect: Block all inbound traffic to pods unless explicitly allowed
# by another NetworkPolicy. Egress is not restricted.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${POLICY_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: gp-copilot
    gp-copilot/responder: networkpolicy-generator
  annotations:
    gp-copilot/generated-at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  # No ingress rules = deny all inbound traffic
EOF
fi

echo ""
echo -e "${GREEN}  Generated: $OUTPUT${NC}"
echo -e "${GREEN}  Policy name: $POLICY_NAME${NC}"
echo ""

# --- Show the generated YAML ---
echo -e "${CYAN}--- Generated Policy ---${NC}"
cat "$OUTPUT"
echo -e "${CYAN}--- End ---${NC}"
echo ""

# --- Check for existing policies in namespace ---
echo -e "${CYAN}Existing NetworkPolicies in ${NAMESPACE}:${NC}"
EXISTING=$(kubectl get networkpolicy -n "$NAMESPACE" --no-headers 2>/dev/null || echo "")
if [[ -z "$EXISTING" ]]; then
    echo -e "  ${YELLOW}(none)${NC}"
else
    echo "$EXISTING" | while read -r line; do
        echo -e "  $line"
    done
fi
echo ""

# --- Apply if requested ---
if [[ "$APPLY" == true ]]; then
    echo -e "${CYAN}Applying policy to cluster...${NC}"
    kubectl apply -f "$OUTPUT"
    echo -e "${GREEN}  Applied: $POLICY_NAME in $NAMESPACE${NC}"
    echo ""
    echo -e "${CYAN}To remove:${NC}"
    echo -e "  kubectl delete networkpolicy $POLICY_NAME -n $NAMESPACE"
else
    echo -e "${YELLOW}Policy saved to file but NOT applied.${NC}"
    echo -e "${YELLOW}To apply:${NC}"
    echo -e "  kubectl apply -f $OUTPUT"
    echo -e "  # Or re-run with --apply flag"
fi
