#!/usr/bin/env bash
# =============================================================================
# scope-rbac.sh — Audit and reduce overly permissive RBAC
# =============================================================================
# Implements: CAPABILITIES.md Responder #8 (RBAC Scoper)
# Rank: C (JADE approval required when automated)
#
# Audits RBAC for wildcard permissions, cluster-admin bindings, dangerous
# service accounts, and unused bindings. Can generate scoped replacements
# but NEVER auto-applies destructive changes.
#
# Usage:
#   bash scope-rbac.sh                              # audit all RBAC
#   bash scope-rbac.sh --namespace production       # namespace-scoped roles only
#   bash scope-rbac.sh --fix ROLENAME               # generate scoped replacement
#   bash scope-rbac.sh --output report.md
# =============================================================================
set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

# --- Defaults ---
NAMESPACE=""
FIX_ROLE=""
OUTPUT=""
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)

# --- Usage ---
usage() {
    cat <<'USAGE'
Usage: scope-rbac.sh [OPTIONS]

Options:
  --namespace NS      Only audit namespace-scoped Roles/RoleBindings
  --fix ROLENAME      Generate a scoped replacement for a ClusterRole
  --output FILE       Save report to file (markdown)
  -h, --help          Show this help

Checks:
  1. ClusterRoles with wildcard verbs or resources (skips system: prefixed)
  2. RoleBindings/ClusterRoleBindings granting cluster-admin
  3. ServiceAccounts with default automountServiceAccountToken
  4. Roles with secrets/configmaps write access
  5. Unused ClusterRoleBindings (subjects that don't exist)

Examples:
  bash scope-rbac.sh                               # full cluster RBAC audit
  bash scope-rbac.sh --namespace production         # namespace-scoped only
  bash scope-rbac.sh --fix my-overpermissive-role   # generate replacement
  bash scope-rbac.sh --output rbac-report.md        # save report
USAGE
    exit "${1:-0}"
}

# --- Parse args ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --namespace)  NAMESPACE="$2"; shift 2 ;;
        --fix)        FIX_ROLE="$2"; shift 2 ;;
        --output)     OUTPUT="$2"; shift 2 ;;
        -h|--help)    usage 0 ;;
        *)            echo -e "${RED}ERROR: Unknown option: $1${NC}"; usage 1 ;;
    esac
done

# --- Fix mode: generate scoped replacement ---
if [[ -n "$FIX_ROLE" ]]; then
    echo -e "${CYAN}Generating scoped replacement for ClusterRole: $FIX_ROLE${NC}"
    echo ""

    if ! kubectl get clusterrole "$FIX_ROLE" &>/dev/null; then
        echo -e "${RED}ERROR: ClusterRole '$FIX_ROLE' not found${NC}"
        exit 1
    fi

    # Get current rules
    kubectl get clusterrole "$FIX_ROLE" -o json | python3 -c "
import sys, json

role = json.load(sys.stdin)
name = role['metadata']['name']
rules = role.get('rules', [])

print(f'# Current rules for ClusterRole: {name}')
print(f'# Total rules: {len(rules)}')
print()

has_wildcards = False
for i, rule in enumerate(rules):
    api_groups = rule.get('apiGroups', [])
    resources = rule.get('resources', [])
    verbs = rule.get('verbs', [])
    if '*' in api_groups or '*' in resources or '*' in verbs:
        has_wildcards = True
        print(f'# Rule {i} (HAS WILDCARDS):')
    else:
        print(f'# Rule {i}:')
    print(f'#   apiGroups: {api_groups}')
    print(f'#   resources: {resources}')
    print(f'#   verbs: {verbs}')
    print()

if not has_wildcards:
    print('# No wildcard rules found. This role may already be scoped.')
    print()

# Generate replacement
print('---')
print(f'# REPLACEMENT ClusterRole for: {name}')
print(f'# Generated by GP-Copilot scope-rbac.sh')
print(f'# REVIEW CAREFULLY before applying -- this is a starting point.')
print(f'# Adjust apiGroups, resources, and verbs to match actual usage.')
print()
print('apiVersion: rbac.authorization.k8s.io/v1')
print('kind: ClusterRole')
print('metadata:')
print(f'  name: {name}-scoped')
print('  labels:')
print('    app.kubernetes.io/managed-by: gp-copilot')
print('    gp-copilot/responder: rbac-scoper')
print('    gp-copilot/replaces: "%s"' % name)
print('rules:')

for rule in rules:
    api_groups = rule.get('apiGroups', [])
    resources = rule.get('resources', [])
    verbs = rule.get('verbs', [])

    # Replace wildcards with common safe defaults
    if '*' in api_groups:
        api_groups = ['', 'apps', 'batch']
    if '*' in resources:
        resources = ['pods', 'services', 'deployments', 'configmaps']
    if '*' in verbs:
        verbs = ['get', 'list', 'watch']

    ag = ', '.join('"%s"' % g for g in api_groups)
    rs = ', '.join('"%s"' % r for r in resources)
    vs = ', '.join('"%s"' % v for v in verbs)
    print('  - apiGroups: [%s]' % ag)
    print('    resources: [%s]' % rs)
    print('    verbs: [%s]' % vs)
"

    FIX_OUTPUT="clusterrole-${FIX_ROLE}-scoped-${TIMESTAMP}.yaml"
    kubectl get clusterrole "$FIX_ROLE" -o json | python3 -c "
import sys, json

role = json.load(sys.stdin)
name = role['metadata']['name']
rules = role.get('rules', [])

lines = []
lines.append('apiVersion: rbac.authorization.k8s.io/v1')
lines.append('kind: ClusterRole')
lines.append('metadata:')
lines.append(f'  name: {name}-scoped')
lines.append('  labels:')
lines.append('    app.kubernetes.io/managed-by: gp-copilot')
lines.append('    gp-copilot/responder: rbac-scoper')
lines.append('rules:')

for rule in rules:
    api_groups = rule.get('apiGroups', [])
    resources = rule.get('resources', [])
    verbs = rule.get('verbs', [])

    if '*' in api_groups:
        api_groups = ['', 'apps', 'batch']
    if '*' in resources:
        resources = ['pods', 'services', 'deployments', 'configmaps']
    if '*' in verbs:
        verbs = ['get', 'list', 'watch']

    ag = ', '.join('"%s"' % g for g in api_groups)
    rs = ', '.join('"%s"' % r for r in resources)
    vs = ', '.join('"%s"' % v for v in verbs)
    lines.append('  - apiGroups: [%s]' % ag)
    lines.append('    resources: [%s]' % rs)
    lines.append('    verbs: [%s]' % vs)

print('\n'.join(lines))
" > "$FIX_OUTPUT"

    echo ""
    echo -e "${GREEN}Scoped replacement saved to: $FIX_OUTPUT${NC}"
    echo -e "${YELLOW}DO NOT auto-apply. Review the file and adjust to actual usage.${NC}"
    echo -e "${CYAN}To apply:${NC}"
    echo -e "  kubectl apply -f $FIX_OUTPUT"
    echo -e "  # Then update bindings to reference '${FIX_ROLE}-scoped' instead of '${FIX_ROLE}'"
    exit 0
fi

# =============================================================================
# AUDIT MODE
# =============================================================================

# Collect all findings for report
REPORT_LINES=()
CRITICAL_COUNT=0
WARNING_COUNT=0
PASS_COUNT=0

add_finding() {
    local severity="$1"
    local message="$2"
    REPORT_LINES+=("${severity}|${message}")
    case "$severity" in
        CRITICAL) ((CRITICAL_COUNT++)) || true ;;
        WARNING)  ((WARNING_COUNT++)) || true ;;
        PASS)     ((PASS_COUNT++)) || true ;;
    esac
}

echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}  RBAC AUDIT${NC}"
if [[ -n "$NAMESPACE" ]]; then
    echo -e "${CYAN}  Scope: namespace=$NAMESPACE${NC}"
else
    echo -e "${CYAN}  Scope: cluster-wide${NC}"
fi
echo -e "${CYAN}============================================${NC}"
echo ""

# --- Check 1: ClusterRoles with wildcard permissions ---
echo -e "${CYAN}[1/5] ClusterRoles with wildcard permissions (skipping system: prefixed)...${NC}"

kubectl get clusterroles -o json | python3 -c "
import sys, json

data = json.load(sys.stdin)
found = 0
for cr in data.get('items', []):
    name = cr['metadata']['name']
    if name.startswith('system:'):
        continue
    rules = cr.get('rules', [])
    for rule in rules:
        api_groups = rule.get('apiGroups', [])
        resources = rule.get('resources', [])
        verbs = rule.get('verbs', [])
        wildcards = []
        if '*' in api_groups: wildcards.append('apiGroups=*')
        if '*' in resources: wildcards.append('resources=*')
        if '*' in verbs: wildcards.append('verbs=*')
        if wildcards:
            found += 1
            print("WILDCARD|%s|%s" % (name, "  ".join(wildcards)))
            break

if found == 0:
    print('NONE')
" | while IFS='|' read -r status name detail; do
    if [[ "$status" == "NONE" ]]; then
        echo -e "  ${GREEN}PASS: No non-system ClusterRoles with wildcards${NC}"
        add_finding "PASS" "No non-system ClusterRoles with wildcard permissions"
    elif [[ "$status" == "WILDCARD" ]]; then
        echo -e "  ${RED}CRITICAL: $name — $detail${NC}"
        add_finding "CRITICAL" "ClusterRole '$name' has wildcard: $detail"
    fi
done

echo ""

# --- Check 2: Bindings granting cluster-admin ---
echo -e "${CYAN}[2/5] Bindings granting cluster-admin...${NC}"

kubectl get clusterrolebindings -o json | python3 -c "
import sys, json

data = json.load(sys.stdin)
found = 0
for crb in data.get('items', []):
    name = crb['metadata']['name']
    if name.startswith('system:'):
        continue
    role_ref = crb.get('roleRef', {})
    if role_ref.get('name') == 'cluster-admin':
        subjects = crb.get('subjects', [])
        for s in subjects:
            found += 1
            kind = s.get('kind', '?')
            sname = s.get('name', '?')
            ns = s.get('namespace', 'cluster-wide')
            print(f'BINDING|{name}|{kind}/{sname} (ns: {ns})')

if found == 0:
    print('NONE')
" | while IFS='|' read -r status binding detail; do
    if [[ "$status" == "NONE" ]]; then
        echo -e "  ${GREEN}PASS: No non-system cluster-admin bindings${NC}"
    elif [[ "$status" == "BINDING" ]]; then
        echo -e "  ${RED}CRITICAL: $binding — grants cluster-admin to $detail${NC}"
    fi
done

# Also check namespace-level RoleBindings
if [[ -n "$NAMESPACE" ]]; then
    NS_FLAG="-n $NAMESPACE"
else
    NS_FLAG="--all-namespaces"
fi

kubectl get rolebindings $NS_FLAG -o json 2>/dev/null | python3 -c "
import sys, json

data = json.load(sys.stdin)
found = 0
for rb in data.get('items', []):
    name = rb['metadata']['name']
    ns = rb['metadata'].get('namespace', '?')
    role_ref = rb.get('roleRef', {})
    if role_ref.get('name') == 'cluster-admin':
        subjects = rb.get('subjects', [])
        for s in subjects:
            found += 1
            kind = s.get('kind', '?')
            sname = s.get('name', '?')
            print(f'BINDING|{ns}/{name}|{kind}/{sname}')

if found == 0:
    print('NONE')
" | while IFS='|' read -r status binding detail; do
    if [[ "$status" == "BINDING" ]]; then
        echo -e "  ${RED}CRITICAL: RoleBinding $binding — grants cluster-admin to $detail${NC}"
    fi
done

echo ""

# --- Check 3: ServiceAccounts with automountServiceAccountToken ---
echo -e "${CYAN}[3/5] ServiceAccounts with automountServiceAccountToken (default=true)...${NC}"

if [[ -n "$NAMESPACE" ]]; then
    SA_JSON=$(kubectl get serviceaccounts -n "$NAMESPACE" -o json 2>/dev/null)
else
    SA_JSON=$(kubectl get serviceaccounts --all-namespaces -o json 2>/dev/null)
fi

echo "$SA_JSON" | python3 -c "
import sys, json

data = json.load(sys.stdin)
found = 0
for sa in data.get('items', []):
    name = sa['metadata']['name']
    ns = sa['metadata'].get('namespace', '?')
    if name == 'default':
        continue  # Skip default SA (always exists)
    automount = sa.get('automountServiceAccountToken')
    # If not explicitly set, it defaults to true
    if automount is None or automount is True:
        found += 1
        if found <= 10:  # Limit output
            print(f'SA|{ns}/{name}|automountServiceAccountToken not disabled')

if found > 10:
    print(f'TRUNCATED|...and {found - 10} more')
if found == 0:
    print('NONE')
" | while IFS='|' read -r status sa detail; do
    if [[ "$status" == "NONE" ]]; then
        echo -e "  ${GREEN}PASS: All non-default ServiceAccounts have automount disabled${NC}"
    elif [[ "$status" == "SA" ]]; then
        echo -e "  ${YELLOW}WARNING: $sa — $detail${NC}"
    elif [[ "$status" == "TRUNCATED" ]]; then
        echo -e "  ${YELLOW}  $sa${NC}"
    fi
done

echo ""

# --- Check 4: Roles with secrets/configmaps write access ---
echo -e "${CYAN}[4/5] Roles with secrets/configmaps write access...${NC}"

if [[ -n "$NAMESPACE" ]]; then
    ROLES_JSON=$(kubectl get roles -n "$NAMESPACE" -o json 2>/dev/null)
else
    ROLES_JSON=$(kubectl get roles --all-namespaces -o json 2>/dev/null)
fi

# Check both namespace Roles and ClusterRoles
{
    echo "$ROLES_JSON"
    kubectl get clusterroles -o json 2>/dev/null
} | python3 -c "
import sys, json

write_verbs = {'create', 'update', 'patch', 'delete', '*'}
sensitive_resources = {'secrets', 'configmaps'}

found = 0
seen = set()

# Read all JSON objects from stdin
import io
content = sys.stdin.read()

# Split on }{ boundary between two JSON docs
parts = content.split('}\n{')
for i, part in enumerate(parts):
    if i == 0:
        part = part + '}'
    elif i == len(parts) - 1:
        part = '{' + part
    else:
        part = '{' + part + '}'

    try:
        data = json.loads(part)
    except json.JSONDecodeError:
        continue

    for item in data.get('items', []):
        name = item['metadata']['name']
        ns = item['metadata'].get('namespace', 'cluster-wide')
        kind = item.get('kind', 'Role')
        if name.startswith('system:'):
            continue

        key = f'{kind}/{ns}/{name}'
        if key in seen:
            continue
        seen.add(key)

        rules = item.get('rules', [])
        for rule in rules:
            resources = set(rule.get('resources', []))
            verbs = set(rule.get('verbs', []))
            overlap_res = resources & sensitive_resources
            overlap_verb = verbs & write_verbs
            if overlap_res and overlap_verb:
                found += 1
                if found <= 15:
                    print(f'WRITE|{kind} {ns}/{name}|{list(overlap_res)} with verbs {list(overlap_verb)}')
                break

if found > 15:
    print(f'TRUNCATED|...and {found - 15} more|')
if found == 0:
    print('NONE||')
" | while IFS='|' read -r status role detail; do
    if [[ "$status" == "NONE" ]]; then
        echo -e "  ${GREEN}PASS: No roles with secrets/configmaps write access${NC}"
    elif [[ "$status" == "WRITE" ]]; then
        echo -e "  ${YELLOW}WARNING: $role — $detail${NC}"
    elif [[ "$status" == "TRUNCATED" ]]; then
        echo -e "  ${YELLOW}  $role${NC}"
    fi
done

echo ""

# --- Check 5: Unused ClusterRoleBindings ---
echo -e "${CYAN}[5/5] Unused ClusterRoleBindings (subjects that don't exist)...${NC}"

kubectl get clusterrolebindings -o json | python3 -c "
import sys, json, subprocess

data = json.load(sys.stdin)
found = 0

# Get existing service accounts for reference
try:
    sa_result = subprocess.run(
        ['kubectl', 'get', 'serviceaccounts', '--all-namespaces', '-o', 'json'],
        capture_output=True, text=True, timeout=30
    )
    sa_data = json.loads(sa_result.stdout)
    existing_sas = set()
    for sa in sa_data.get('items', []):
        ns = sa['metadata'].get('namespace', '')
        name = sa['metadata']['name']
        existing_sas.add(f'{ns}/{name}')
except Exception:
    existing_sas = None  # Can't verify, skip this check

if existing_sas is None:
    print('SKIP|Could not retrieve ServiceAccounts to verify|')
else:
    for crb in data.get('items', []):
        name = crb['metadata']['name']
        if name.startswith('system:'):
            continue
        subjects = crb.get('subjects', [])
        for s in subjects:
            kind = s.get('kind', '')
            sname = s.get('name', '')
            sns = s.get('namespace', '')
            if kind == 'ServiceAccount':
                key = f'{sns}/{sname}'
                if key not in existing_sas:
                    found += 1
                    if found <= 10:
                        print(f'UNUSED|{name}|references non-existent SA {key}')

    if found > 10:
        print(f'TRUNCATED|...and {found - 10} more|')
    if found == 0:
        print('NONE||')
" | while IFS='|' read -r status binding detail; do
    if [[ "$status" == "NONE" ]]; then
        echo -e "  ${GREEN}PASS: No unused ClusterRoleBindings found${NC}"
    elif [[ "$status" == "SKIP" ]]; then
        echo -e "  ${YELLOW}SKIPPED: $binding${NC}"
    elif [[ "$status" == "UNUSED" ]]; then
        echo -e "  ${RED}CRITICAL: $binding — $detail${NC}"
    elif [[ "$status" == "TRUNCATED" ]]; then
        echo -e "  ${YELLOW}  $binding${NC}"
    fi
done

echo ""

# --- Summary ---
echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}  RBAC AUDIT SUMMARY${NC}"
echo -e "${CYAN}============================================${NC}"
echo -e "  Checks run: 5"
echo -e "  Timestamp:  $(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [[ -n "$NAMESPACE" ]]; then
    echo -e "  Scope:      namespace=$NAMESPACE"
else
    echo -e "  Scope:      cluster-wide"
fi
echo ""
echo -e "${CYAN}To fix a specific ClusterRole:${NC}"
echo -e "  bash scope-rbac.sh --fix ROLENAME"
echo ""

# --- Save report if requested ---
if [[ -n "$OUTPUT" ]]; then
    {
        echo "# RBAC Audit Report"
        echo ""
        echo "| Field | Value |"
        echo "|-------|-------|"
        echo "| Timestamp | $(date -u +%Y-%m-%dT%H:%M:%SZ) |"
        if [[ -n "$NAMESPACE" ]]; then
            echo "| Scope | namespace=$NAMESPACE |"
        else
            echo "| Scope | cluster-wide |"
        fi
        echo "| Generated by | \`scope-rbac.sh\` (GP-Copilot) |"
        echo ""
        echo "## Checks"
        echo ""
        echo "1. ClusterRoles with wildcard permissions (skipping system:)"
        echo "2. Bindings granting cluster-admin"
        echo "3. ServiceAccounts with automountServiceAccountToken default"
        echo "4. Roles with secrets/configmaps write access"
        echo "5. Unused ClusterRoleBindings"
        echo ""
        echo "## Recommendations"
        echo ""
        echo "- Replace wildcard ClusterRoles with scoped versions: \`bash scope-rbac.sh --fix ROLENAME\`"
        echo "- Review all cluster-admin bindings — most should use scoped roles"
        echo "- Set \`automountServiceAccountToken: false\` on ServiceAccounts that don't need API access"
        echo "- Restrict secrets/configmaps write access to only the service accounts that need it"
        echo "- Remove ClusterRoleBindings that reference non-existent subjects"
        echo ""
        echo "---"
        echo "*Generated by GP-Copilot scope-rbac.sh*"
    } > "$OUTPUT"
    echo -e "${GREEN}Report saved to: $OUTPUT${NC}"
fi
