apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  # JSA-FIX: CKV_K8S_21 - Dont use default namespace
  namespace: portfolio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
- kind: ServiceAccount
  name: app-service-account
  # JSA-FIX: CKV_K8S_21 - Dont use default namespace
  namespace: portfolio
