apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  # JSA-FIX: CKV_K8S_21 - Don't use default namespace
  namespace: portfolio
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
