#!/usr/bin/env bash
# check-licenses.sh
# Scan dependencies for copyleft/restricted licenses (pre-deploy).
#
# Usage:
#   bash check-licenses.sh <project-dir> [--strict] [--output report.md]
#
# CKS alignment: Supply chain security — license compliance.
# CNPE alignment: Platform governance — prevent license violations at scale.
#
# What it does:
#   - Runs trivy license scan on the project
#   - Flags copyleft licenses (GPL, AGPL, LGPL, SSPL)
#   - In --strict mode, exits non-zero if copyleft found (use as CI gate)
#   - Generates markdown report
#
# Requires: trivy

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

PROJECT_DIR=""
STRICT=false
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --strict) STRICT=true; shift ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) PROJECT_DIR="$1"; shift ;;
  esac
done

if [[ -z "$PROJECT_DIR" ]]; then
  echo "Usage: bash check-licenses.sh <project-dir> [--strict] [--output report.md]"
  exit 1
fi

if ! command -v trivy &>/dev/null; then
  echo -e "${RED}ERROR: trivy not found.${NC}"
  exit 1
fi

echo ""
echo -e "${BLUE}=== Ghost Protocol — License Compliance Check ===${NC}"
echo "  Project : $PROJECT_DIR"
echo "  Mode    : $(if $STRICT; then echo 'STRICT (CI gate)'; else echo 'advisory'; fi)"
echo ""

# Run trivy license scan
SCAN_OUTPUT=$(trivy fs "$PROJECT_DIR" --scanners license --format json 2>/dev/null || true)

if [[ -z "$SCAN_OUTPUT" ]]; then
  echo -e "${YELLOW}No license data available (trivy may not support license scanning for this project type).${NC}"
  echo "  Fallback: manually check package.json / requirements.txt / go.mod for license fields."
  exit 0
fi

python3 - "$SCAN_OUTPUT" "$STRICT" "$OUTPUT" <<'PYEOF'
import json
import sys

scan_data = sys.argv[1]
strict = sys.argv[2] == "True"
output_file = sys.argv[3] if len(sys.argv) > 3 and sys.argv[3] else None

try:
    results = json.loads(scan_data)
except json.JSONDecodeError:
    print("No license scan results available.")
    sys.exit(0)

copyleft = ["GPL", "AGPL", "LGPL", "SSPL", "EUPL", "OSL", "CPAL", "RPL"]
permissive = ["MIT", "Apache", "BSD", "ISC", "Unlicense", "CC0", "MPL"]

flagged = []
all_licenses = []

for result in results.get("Results", []):
    for lic in result.get("Licenses", []):
        name = lic.get("Name", "unknown")
        pkg = lic.get("PkgName", "unknown")
        category = lic.get("Category", "unknown")
        severity = lic.get("Severity", "UNKNOWN")

        entry = {"package": pkg, "license": name, "category": category, "severity": severity}
        all_licenses.append(entry)

        for cl in copyleft:
            if cl.lower() in name.lower():
                flagged.append(entry)
                break

# Print summary
print(f"Total packages scanned: {len(all_licenses)}")
print(f"Copyleft/restricted: {len(flagged)}")
print(f"Permissive: {len(all_licenses) - len(flagged)}")
print()

if flagged:
    print("⚠ Copyleft licenses found:")
    for f in flagged:
        print(f"  • {f['package']} — {f['license']} ({f['category']})")
    print()
    print("Action required:")
    print("  - If shipping proprietary software: replace these dependencies")
    print("  - If open-source project: verify compatibility with your license")
    print("  - If internal only: copyleft usually not an issue")
else:
    print("✓ No copyleft license issues detected.")

# Generate report if requested
if output_file:
    with open(output_file, "w") as f:
        f.write("# License Compliance Report\n\n")
        f.write(f"**Project:** {sys.argv[1][:50]}...\n")
        f.write(f"**Packages scanned:** {len(all_licenses)}\n")
        f.write(f"**Copyleft found:** {len(flagged)}\n\n")
        if flagged:
            f.write("## Copyleft/Restricted Licenses\n\n")
            f.write("| Package | License | Category |\n")
            f.write("|---------|---------|----------|\n")
            for fl in flagged:
                f.write(f"| {fl['package']} | {fl['license']} | {fl['category']} |\n")
        f.write("\n---\n*Generated by Ghost Protocol check-licenses.sh*\n")
    print(f"\nReport written to: {output_file}")

if strict and flagged:
    sys.exit(1)

PYEOF

EXIT_CODE=$?

echo ""
if [[ $EXIT_CODE -ne 0 ]] && $STRICT; then
  echo -e "${RED}STRICT MODE: Copyleft licenses found. Failing CI gate.${NC}"
  exit 1
fi

echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review flagged licenses for your use case"
echo "  2. Replace copyleft deps if shipping proprietary"
echo "  3. Add to CI: bash check-licenses.sh \$PROJECT --strict"
echo ""
