apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-host-namespaces
  annotations:
    policies.kyverno.io/title: Disallow Host Namespaces
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Host namespaces (hostNetwork, hostPID, hostIPC) allow access to shared
      resources on the node and must be disallowed.
    checkov.id: CKV_K8S_19
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: host-network
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Sharing the host network namespace is disallowed."
        pattern:
          spec:
            =(hostNetwork): false
    - name: host-pid
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Sharing the host PID namespace is disallowed."
        pattern:
          spec:
            =(hostPID): false
    - name: host-ipc
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Sharing the host IPC namespace is disallowed."
        pattern:
          spec:
            =(hostIPC): false
