{{- if .Values.podSecurityStandards.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}
    {{- include "portfolio.labels" . | nindent 4 }}
{{- end }}
