{{- if .Values.networkPolicy.enabled }}
# Default deny-all network policy for namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "portfolio.fullname" . }}-default-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# Allow ingress from ingress controller to UI and API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "portfolio.fullname" . }}-allow-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.api.targetPort }}
        - protocol: TCP
          port: {{ .Values.service.ui.targetPort }}
---
# Allow API to communicate with ChromaDB
{{- if .Values.chroma.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "portfolio.fullname" . }}-api-to-chroma
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chroma
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "portfolio.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: api
      ports:
        - protocol: TCP
          port: {{ .Values.chroma.service.port }}
---
{{- end }}
# Allow DNS resolution for all pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "portfolio.fullname" . }}-allow-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Allow API to access external services (OpenAI, ElevenLabs, D-ID)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "portfolio.fullname" . }}-api-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    - Egress
  egress:
    # HTTPS for external APIs (OpenAI, ElevenLabs, D-ID)
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # HTTP for package downloads during startup (if needed)
    - to: []
      ports:
        - protocol: TCP
          port: 80
    {{- if .Values.chroma.enabled }}
    # Allow API to connect to ChromaDB
    - to:
        - podSelector:
            matchLabels:
              {{- include "portfolio.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: chroma
      ports:
        - protocol: TCP
          port: {{ .Values.chroma.service.port }}
    {{- end }}
{{- end }}
