{{- if .Values.resourceQuotas.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "portfolio.fullname" . }}-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuotas.hard | nindent 4 }}
    # Additional security-focused limits
    pods: "10"
    secrets: "20"
    configmaps: "20"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "portfolio.fullname" . }}-limits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  limits:
  # Container limits
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
      ephemeral-storage: "100Mi"
    max:
      cpu: "2"
      memory: "2Gi"
      ephemeral-storage: "10Gi"
    min:
      cpu: "10m"
      memory: "64Mi"
      ephemeral-storage: "10Mi"
  
  # Pod limits
  - type: Pod
    max:
      cpu: "4"
      memory: "4Gi"
      ephemeral-storage: "20Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
      ephemeral-storage: "50Mi"
  
  # PVC limits  
  - type: PersistentVolumeClaim
    max:
      storage: "50Gi"
    min:
      storage: "1Gi"
{{- end }}