# This file will be managed by SOPS in production
# For development, create manually with kubectl or use Helm --set
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio.fullname" . }}-api-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded secrets - will be managed by external-secrets or SOPS
  OPENAI_API_KEY: ""
  ELEVENLABS_API_KEY: ""
  DID_API_KEY: ""