apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: anthra-log-ingest-pdb
  namespace: anthra
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: anthra-log-ingest
