apiVersion: v1
kind: Service
metadata:
  name: anthra-log-ingest
  namespace: anthra
  labels:
    app: anthra-log-ingest
spec:
  type: ClusterIP
  selector:
    app: anthra-log-ingest
  ports:
    - name: http
      port: 9090
      targetPort: 9090
