# Example secrets - Copy to 02-secrets.yaml and add your real API keys
# kubectl create secret generic portfolio-api-secrets \
#   --from-literal=CLAUDE_API_KEY="your-claude-key" \
#   --from-literal=OPENAI_API_KEY="your-openai-key" \
#   --from-literal=ELEVENLABS_API_KEY="your-elevenlabs-key" \
#   --from-literal=DID_API_KEY="your-did-key" \
#   -n portfolio

apiVersion: v1
kind: Secret
metadata:
  name: portfolio-api-secrets
  namespace: portfolio
type: Opaque
stringData:
  CLAUDE_API_KEY: "REPLACE_WITH_YOUR_CLAUDE_API_KEY"
  OPENAI_API_KEY: "REPLACE_WITH_YOUR_OPENAI_API_KEY"
  ELEVENLABS_API_KEY: "REPLACE_WITH_YOUR_ELEVENLABS_API_KEY"
  DID_API_KEY: "REPLACE_WITH_YOUR_DID_API_KEY"
