apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - pdb.yaml
