apiVersion: v1
kind: Service
metadata:
  name: anthra-ui
  namespace: anthra
  labels:
    app: anthra-ui
spec:
  type: ClusterIP
  selector:
    app: anthra-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
